---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /opt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubernetes-node1
          - kubernetes-node2

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-server
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  volumeName: "prometheus-pv"
  resources:
    requests:
      storage: 3G


